import { PATH_AUTHORIZATION, PATH_FORGOT_PASSWORD, PATH_REG } from './path-url';
import {
  TEXT_AUTH_RESPONSE,
  TEXT_RESET_SUCCES,
  TEXT_RESPONSE_FALSE,
  TEXT_RESPONSE_FALSE_TWO,
  TEXT_RESPONSE_SUCCES,
  TITLE_RESET_SUCCES,
  TITLE_RESPONSE_FALSE_TWO,
  TITLE_RESPONSE_SUCCES,
} from './response-request';
import { TITLE_RESPONSE_FALSE } from './text';
import { TEXT_BUTTON_RESPONSE_FALSE, TEXT_BUTTON_RESPONSE_FALSE_TWO, TEXT_BUTTON_RESPONSE_SUCCES } from './text-button';

export const dataResetForms = [
  {
    title: TITLE_RESPONSE_SUCCES,
    text: TEXT_RESPONSE_SUCCES,
    textButton: TEXT_BUTTON_RESPONSE_SUCCES,
    path: PATH_AUTHORIZATION,
  },
  {
    title: TITLE_RESPONSE_FALSE,
    text: TEXT_RESPONSE_FALSE,
    textButton: TEXT_BUTTON_RESPONSE_FALSE,
    path: PATH_REG,
  },
  {
    title: TITLE_RESPONSE_FALSE_TWO,
    text: TEXT_RESPONSE_FALSE_TWO,
    textButton: TEXT_BUTTON_RESPONSE_FALSE_TWO,
    path: PATH_REG,
  },
];

export const dataResetPassword = [
  {
    title: TITLE_RESET_SUCCES,
    text: TEXT_RESET_SUCCES,
    textButton: TEXT_BUTTON_RESPONSE_SUCCES,
    path: PATH_AUTHORIZATION,
  },
  {
    title: TITLE_RESPONSE_FALSE_TWO,
    text: TEXT_AUTH_RESPONSE,
    textButton: TEXT_BUTTON_RESPONSE_FALSE,
    path: PATH_FORGOT_PASSWORD,
  },
];
